services:
  - type: web
    name: automester-pro-erp
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npx prisma db push && npx prisma db seed && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: PORT
        value: 3000
